/*
    Name        : Koo Tian Yaw
    Description : Programming Concepts and Design I (Assignment Demo)
*/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <time.h>

#pragma warning(disable: 4996) // required to suppress warning of deprecated function call (e.g. scanf)

#define OPERATION_ADDITION       1
#define OPERATION_SUBTRACTION    2
#define OPERATION_MULTIPLICATION 3

#define LEVEL_BEGINNER     1
#define LEVEL_INTERMEDIATE 2
#define LEVEL_ADVANCED     3

#define MENU_EXIT 4

#define NO_OF_QUESTION   10
#define SCORE_MULTIPLIER 10
#define EXCELLENT_SCORE  70

const char CONFIRM_YES       = 'Y';
const char INVALID_MESSAGE[] = "\aInvalid selection. Please try again.";
const char ERROR_MESSAGE[]   = "Something went wrong. Please contact system administrator.";

void displayOperationMenu(int operation);
void displayLevelMenu(int level);
void displayQuizMenu(int operation, int level);
void displayQuizQuestion(int operation, int nthQuestion, int leftOperand, int rightOperand);

int operationMenuSelection();
int levelMenuSelection(int operation);

int isValidOperation(int operation);
int isValidLevel(int level);

int getOperandByLevel(int level);
int getSystemAnswer(int operation, int leftOperand, int rightOperand);

int runQuizGenerator(int operation, int level);

void main()
{
    int menuSelection,
        subMenuSelection,
        currentOperation,
        currentLevel;

    do
    {
        system("cls");

        menuSelection    = operationMenuSelection();
        currentOperation = menuSelection;

        if (isValidOperation(currentOperation))
        {
            do
            {
                system("cls");

                subMenuSelection = levelMenuSelection(currentOperation);
                currentLevel     = subMenuSelection;

                if (isValidLevel(currentLevel))
                {
                    while (isValidLevel(currentLevel))
                    {
                        system("cls");

                        int  score = runQuizGenerator(currentOperation, currentLevel);
                        char shouldContinue;

                        printf("\nYour score is %d / %d. ", score, NO_OF_QUESTION * SCORE_MULTIPLIER);

                        if (score >= EXCELLENT_SCORE && isValidLevel(currentLevel + 1))
                        {
                            rewind(stdin); // clear input buffer to remove the line feed (LF) character generated by the "Enter" key

                            printf("Well done!\nContinue next level? (Press '%c' for YES or any other characters to CANCEL) ", CONFIRM_YES);
                            scanf("%c", &shouldContinue);

                            shouldContinue = toupper(shouldContinue);

                            if (shouldContinue == CONFIRM_YES)
                                currentLevel++;
                            else
                                break;
                        }
                        else
                        {
                            rewind(stdin); // clear input buffer to remove the line feed (LF) character generated by the "Enter" key

                            printf("Try again? (Press '%c' for YES or any other characters to CANCEL) ", CONFIRM_YES);
                            scanf("%c", &shouldContinue);

                            shouldContinue = toupper(shouldContinue);

                            if (shouldContinue != CONFIRM_YES)
                                break;
                        }
                    }
                }
                else if (subMenuSelection == MENU_EXIT)
                {
                    break;
                }
                else
                {
                    puts(INVALID_MESSAGE);
                    system("pause");
                }
            } while (subMenuSelection != MENU_EXIT);
        }
        else if (menuSelection == MENU_EXIT)
        {
            puts("\nBye bye~");
            break;
        }
        else
        {
            puts(INVALID_MESSAGE);
            system("pause");
        }
    } while (menuSelection != MENU_EXIT);

    system("pause");
}

void displayOperationMenu(int operation)
{
    if (operation == OPERATION_ADDITION)
        puts("Operation : +");
    else if (operation == OPERATION_SUBTRACTION)
        puts("Operation : -");
    else if (operation == OPERATION_MULTIPLICATION)
        puts("Operation : x");
}

void displayLevelMenu(int level)
{
    printf("Level     : ");

    switch (level)
    {
        case LEVEL_BEGINNER:
            puts("BEGINNER");
            break;
        case LEVEL_INTERMEDIATE:
            puts("INTERMEDIATE");
            break;
        case LEVEL_ADVANCED:
            puts("ADVANCED");
            break;
        default:
            puts(ERROR_MESSAGE);
    }
}

void displayQuizMenu(int operation, int level)
{
    displayOperationMenu(operation);
    displayLevelMenu(level);
}

void displayQuizQuestion(int operation, int nthQuestion, int leftOperand, int rightOperand)
{
    printf("\nQuestion %d of %d\n", nthQuestion, NO_OF_QUESTION);

    if (operation == OPERATION_ADDITION)
    {
        printf("%d + %d = ", leftOperand, rightOperand);
    }
    else if (operation == OPERATION_SUBTRACTION)
    {
        printf("%d - %d = ", leftOperand, rightOperand);
    }
    else if (operation == OPERATION_MULTIPLICATION)
    {
        printf("%d x %d = ", leftOperand, rightOperand);
    }
    else
    {
        printf(ERROR_MESSAGE);
    }
}

int operationMenuSelection()
{
    int operation;

    puts("Operation");
    puts("=========");
    puts("1) Addition");
    puts("2) Subtraction");
    puts("3) Multiplication");
    puts("4) Exit\n");

    printf("Your selection: ");
    scanf("%d", &operation);

    return operation;
}

int levelMenuSelection(int operation)
{
    int level;

    displayOperationMenu(operation);

    puts("");
    puts("Level");
    puts("=====");
    puts("1) Beginner");
    puts("2) Intermediate");
    puts("3) Advanced");
    puts("4) Back\n");

    printf("Your selection: ");
    scanf("%d", &level);

    return level;
}

int isValidOperation(int operation)
{
    return operation == OPERATION_ADDITION    ||
           operation == OPERATION_SUBTRACTION ||
           operation == OPERATION_MULTIPLICATION;
}

int isValidLevel(int level)
{
    return level == LEVEL_BEGINNER     ||
           level == LEVEL_INTERMEDIATE ||
           level == LEVEL_ADVANCED;
}

int getOperandByLevel(int level)
{
    return level == LEVEL_BEGINNER ?
            rand() % 9   + 1 :  // One digit (1 - 9)
           level == LEVEL_INTERMEDIATE ?
            rand() % 90  + 10 : // Double digit (10 - 99)
            rand() % 900 + 100; // Triple digit (100 - 999)
}

int getSystemAnswer(int operation, int leftOperand, int rightOperand)
{
    return operation == OPERATION_ADDITION ?
            leftOperand + rightOperand :
           operation == OPERATION_SUBTRACTION ?
            leftOperand - rightOperand :
           operation == OPERATION_MULTIPLICATION ?
            leftOperand * rightOperand : 0; // 0 (dummy value)
}

int runQuizGenerator(int operation, int level)
{
    int noOfCorrectAnswer = 0;

    for (int n = 1; n <= NO_OF_QUESTION; n++)
    {
        system("cls");
        srand(time(NULL));

        int leftOperand  = getOperandByLevel(level),
            rightOperand = getOperandByLevel(level),
            systemAnswer = getSystemAnswer(operation, leftOperand, rightOperand),
            userAnswer;

        displayQuizMenu(operation, level);
        displayQuizQuestion(operation, n, leftOperand, rightOperand);
        scanf("%d", &userAnswer);

        if (userAnswer == systemAnswer)
        {
            noOfCorrectAnswer++;
            puts("\nYou've got it right! ^_^\n");
        }
        else
        {
            puts("\n\aWrong answer. =(\n");
        }

        system("pause");
    }

    return noOfCorrectAnswer * SCORE_MULTIPLIER;
}
